### ISSUE TITLE
Project not on track 

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project-breadnbeer#10]
Please give out a detailed timeline and plan. We have not seen any commits to your project on the past week.

**Comment by moriarty** [comment]
Please get something new into your master branch ASAP. And continue development in an open manor in which we can monitor progress and ensure that the group members are distributing the work evenly.

**Comment by moriarty** [comment]
@Chetansidnal you can close issues when you've completed them.
We will reopen them or open new ones if we need to.

They've merged to master so I will close this.
