### ISSUE TITLE
Update README ( have members dropped out? )

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-breadnbeer#30]
Related to: #17 **Work distribution**

If members have dropped out please let **That** member:
1. Remove themselves from the README, and tag @argenos and myself (@moriarty) in the merge request.
2. Send the professor an email and (and cc: us)

The remaining group members should contact @argenos on campus if you're interested in merging with another group.

If no members have dropped out, and you're just not attending courses please contribute to the project and commend #17 and close this issue.

**Comment by moriarty** [comment]
I can't seem to assign @aaqib49 to this issue.

**Comment by argenos** [comment]
I've removed him from the team already. Since it's hard to get an answer from the students here, I'm officially sending an email.

**Comment by Chetansidnal** [comment]
hi , is it possible for us to merge with other team ??, i heard that one guy from team just_a_bakery had left already.

**Comment by argenos** [comment]
Please check your email, I have sent instructions to you and your teammates on how to handle this.

**Comment by Chetansidnal** [comment]
yes updated the read me file
