### ISSUE TITLE
Git branching model

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project-breadnbeer#4]
Please follow a [git branching model](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by argenos** [comment]
Please clean up your branches (the branch from @Chetansidnal is still there), you can close the issue once that is done. 
A few comments:
* You need to merge back to master more often, e.g. every 2 or 3 days. We are mostly taking a look at your master branch when grading
* Try using prefixes for your next branches, it will make their purpose clearer.

**Comment by Chetansidnal** [comment]
yes , I have deleted chetan branch now.

**Comment by argenos** [comment]
@jonkoi your branch names are not following the git branching model! e.g the  `newer` branch

**Comment by argenos** [comment]
@Chetansidnal @jonkoi in general, please use more descriptive names in your pull requests and take a look at [this](https://chris.beams.io/posts/git-commit/) for your commit messages.

**Comment by jonkoi** [comment]
Branches cleaned up
