### ISSUE TITLE
Add the email(s) you commit with to GitHub

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-breadnbeer#8]
Please see:

HBRS-MAAS/project-just_a_bakery#8

**Comment by aaqib49** [comment]
Updated the commit Email IDs in git.

**Comment by argenos** [comment]
I think the email for @jonkoi is still missing.

**Comment by argenos** [comment]
@jonkoi you still have branches where your email still doesn't show up
![image](https://user-images.githubusercontent.com/5426039/33566332-e87c95e6-d91f-11e7-98d9-8eb1f3e9183f.png)

**Comment by jonkoi** [comment]
Wrong email in local git. Hope it works now
